# docker-compose.yml

services:
  db:
    image: postgres:13
    container_name: housing_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: housing_api
    restart: always
    env_file:
      - .env
    ports:
      - "${API_PORT}:8001"
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
      "

volumes:
  db_data:
